### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zwhitchcox** [prakhar1989/Algorithms#5]
I'm getting this error:

```sh
  File "test.py", line 42
    print dijkstra (graph, 1)
                 ^
SyntaxError: invalid syntax
```

when I use this code

```py
from heapq import heappush, heappop
graph = {
    's' : {'t':6, 'y':7},
    't' : {'x':5, 'z':4, 'y':8 },
    'y' : {'z':9, 'x':3},
    'z' : {'x':7, 's': 2},
    'x' : {'t':2}
}

def read_graph(file):
    graph = dict()
    with open(file) as f:
        for l in f:
            (u, v, w) = l.split()
            if int(u) not in graph:
                graph[int(u)] = dict()
            graph[int(u)][int(v)] = int(w)
    return graph

inf = float('inf')
def dijkstra(graph, s):
    n = len(graph.keys())
    dist = dict()
    Q = list()

    for v in graph:
        dist[v] = inf
    dist[s] = 0

    heappush(Q, (dist[s], s))

    while Q:
        d, u = heappop(Q)
        if d < dist[u]:
            dist[u] = d
        for v in graph[u]:
            if dist[v] > dist[u] + graph[u][v]:
                dist[v] = dist[u] + graph[u][v]
                heappush(Q, (dist[v], v))
    return dist

print dijkstra(graph, 1)
```

All I did was omit the read file line and uncomment the graph.

**Comment by zwhitchcox** [comment]
That was fixed with this ```print(dijkstra(graph, 1))```, but now, I'm getting this error:

```sh
exec error: Error: Command failed: /bin/sh -c echo hi | sudo -S -u world python3 packages/custom/algos/server/playground/test.py
Traceback (most recent call last):
  File "packages/custom/algos/server/playground/test.py", line 42, in <module>
    print(dijkstra(graph, 1))
  File "packages/custom/algos/server/playground/test.py", line 36, in dijkstra
    for v in graph[u]:
KeyError: 1
```

**Comment by prakhar1989** [comment]
You're trying to read the graph from a file whereas the graph already exists in the definition. Let me know if you are still facing this issue.
